# These are supported funding model platforms

github: [f] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://donate.stripe.com/aFa8wO4NF2S96jDfn4dMI09'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
